---
title: "Tao Analysis Solutions"
author: "Segun"
date: "21 de febrero de 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Chapter 2

**Pg 24** Prove that the sum of two natural numbers is again a natural number?


*Solution*: Let $n$ and $m$ be natural numbers. Using induction on $n$ and keeping $m$ fixed,we have the base case to be $0 + m := m$ which is a natural number as desired (by definition of addition and **Axiom 2.1**). 

Now we assume inductively $n+m$ is a natural number. We have to show that $(n++)+m$ is also a natural number. But $(n++) + m = (n+m)++$ by definition of addition and **Axiom 2.2**. However, $n+m$ is a natural number according to the inductive hypothesis and therefore $(n+m)++$ is also a natural number by **Axiom 2.2**.
$\square$

**Pg 26** Prove that $n++ = n+1$ 

*Solution 1*: Let $n$ be a natural number, then $n++ = (n++) + 0 = (n+0)++ = n + (0++) = n+1$ according to **Lemma 2.2.2**, definition of addition, **Lemma 2.2.3** and definition of increment respectively. $\square$

*Solution 2*: Using induction on $n$, we have to show that $0++ = 0+1$ for the base case. However, $0++ = 1 = 0 + 1$ by definitions of increment, and addition respectively and so the base case is done. 

Now suppose inductively that $n++ = n+1$, we have to show that $(n++) ++ = (n++) +1$.

From the RHS, $(n++)+1 = (n+1)++ = (n++)++$ by definition of addition and the inductive hypothesis repectively. $\square$

**Exercise 2.2.1.** (Addition is associative). Prove that for any natural numbers $a$, $b$, $c$, we have $(a + b) + c = a + (b + c)$.

*Solution*: Using induction on $a$ and keeping $a$ and $c$ fixed. For the base case, we want to show that $(0+b) + c = 0+(b+c)$. However, $(0+b) + c  = b+c = 0 + (b+c)$ by the definition of addition.

Now suppose inductively that $(a+b)+c = a+(b+c)$, we have to show that $((a++)+b)+c = (a++) + (b+c)$.

From the RHS, we have that $(a++) + (b+c) = (a+(b+c))++ = ((a+b)+c)++$ by the definition of addition and the inductive hypothesis respectively. Furthermore, $((a+b)+c)++ = (((a+b)++)+c) = ((a++)+b)+c$ by definition of addition. $\square$

**Exercise 2.2.2.** Let $a$ be a positive number. Then there exists exactly one natural number $b$ such that $b++ = a$.

*Solution:* First we prove the existence of a natural number $b$ such that $b{++} = a$ for $a\in \mathbb{N}^+$ using induction on $a$. For the base case $a = 1$, we want to show that there exists a natural number $b$ such that $b{++} = 1$. Clearly, $0{++} = 1$ so $b = 0$.

Now suppose inductively that for any positive number $a$, there exists a natural number $b$ such that $b{++} = a$. 

We have to show that there exists a natural number $q$ such that $q++ = a++$. But $a++ = (b++)++$ by the inductive hypothesis, so that $q{++} = (b{++}){++}$ and by **Axiom 2.4**, $q = b{++}$. So that completes the induction and the proof existence.

Now we have to prove the uniqueness of the natural number $b$ such that $b{++} = a$ for $a\in \mathbb{N}^+$. Suppose for the sake of contradiction that there exist $b$, $c$ $\in \mathbb{N}$ with $b\ne c$ such that $b{++} = a$ and $c{++} = a$. Then $b{++} = c{++}$ and by **Axiom 2.4** $b = c$ which is a contradiction. Consequently, there exists exactly one natural number $b$ such that $b{++} = a$  for $a\in \mathbb{N}^+$. $\square$

**Exercise 2.2.3.** Basic properties of order for natural numbers). Let a, b, c be natural numbers. Then
*Solution:*
\begin{enumerate}
\item (Order is reflexive) $a \ge a$.

$a = a + 0$ by \textbf{Lemma 2.2.3} , therefore, $a\ge a$ by definition. $\square$

\item (Order is transitive) If $a \ge b$ and $b \ge c$, then $a \ge c$.

By definition, $a\ge b$ implies that $a = b+d$ and $b \ge c$ implies $b = c + e$, for some $d$, $e$ $\in \mathbb{N}$. Therefore, $a = b + d = (c+e)+d = c +(e+d) \ge c$ by ordering of natural numbers and associativity of addition. $\square$.   

\item (Order is anti-symmetric) If $a \ge b$ and $b \ge a$, then $a = b$.


Since $a \ge b$ and $b \ge a$, we have that $a = b + c$ and $b = a + d$ for some $c$, $d$ $\in \mathbb{N}$. Thus $a = a + c + d$ which implies that $c+d = 0$ by \textbf{Lemma 2.2.2} and that further implies $c = 0$ and $d = 0$ by \textbf{Corollary 2.2.9}. Consequently, $a = b$. $\square$


\item (Addition preserves order) $a \ge b$ if and only if $a + c \ge b + c$.

Because $a\ge b$, $a = b+d$ for some $d \in \mathbb{N}$. Hence $a + c = (b+d) + c = (b+c) + d \ge b+c$ by the cancellation law, associativity of addition and ordering of natural numbers respectively.

Likewise, $a+c \ge b+c$ implies $a+c = (b+c) + e$, for some $e \in \mathbb{N}$. Consequently, $a+c = (b+e) + c$ by associativity of addition. By cancellation law, $a = b + e$ so $a\ge b$. $\square$ 

\item $a < b$ if and only if $a{++} \le b$

\textit{Proof.} Since $a<b$,  then $b = a+n$, for some $n \in \mathbb{N}$ and $b \ne a$. Consequently, $n \ne 0$ by \textbf{Lemma 2.2.2}. Then there exists a number say $m \in \mathbb{N}$ such that $m{++} = n$ by \textbf{Lemma 2.2.10}. So $b = a+n = a + m{++} = (a{++}) + m$ by \textbf{Lemma 2.2.3}. So $a{++} \le b$.

Likewise $a{++} \le b$ implies $b = (a{++}) + n$ for some $n \in \mathbb{N}$. Consequently, $b = a + (n{++})$ by \textbf{Lemma 2.2.3} and by \textbf{Definition 2.2.1} (Addition of natural numbers). But we know that $n{++} \ne 0$ by \textbf{Axiom 2.3} and by implication $b \ne a$. So $a<b$. $\square$

\item $a < b$ if and only if $b = a + d$ for some positive number $d$.

\textit{Proof}. If $a<b$, then $b = a+d$ for some $d\in \mathbb{N}$ and $b\ne a$ by definition. We need to show that $d\ne 0$. Now suppose for the sake of contradiction that $d = 0$. Then $b = a+d$ implies $a = b$ which is a contradition so $d\ne0$. 

Likewise, $b = a+d$, $d \ne 0$ implies $a\le b$ by \textbf{Definition 2.2.11} (Ordering of the natural numbers). We need to show that $b \ne a$. Suppose for the sake of contradiction that $b = a$, then $b = a+d$ implies  $d = 0$ by \textbf{Lemma 2.2.2} which is a contradiction. Hence $b \ne a$ and $a\le b$ so $a<b$. $\square$

\end{enumerate}

**Exercise 2.2.4.** Justify the three statements marked (why?) in the proof of **Proposition 2.2.13**.

\begin{enumerate}
\item $0\le b$ for all $b\in \mathbb{N}$.

\textit{Proof}. Since $b \in \mathbb{N}$, then $b = 0 + b$ by \textbf{Definition 2.2.1} (Addition of natural numbers) so $0\le b$ by \textbf{Definition 2.2.11} (Ordering of the natural numbers). 

\item  If $a>b$, then $a{++} > b$

\textit{Proof}. Because $a{++}>a$ and $a>b$. Then by \textbf{Proposition 2.2.12} (Transitivity of order), $a{++} > b$. 

\item If $a = b$, the $a{++} =  b+d$

\textit{Proof}. Because $a{++}>a$ implies $a{++}>b$  since $a=b$. 

\end{enumerate}

**Exercise 2.2.5.** Prove **Proposition 2.2.14**. (Strong principle of induction). Let $m_0$ be a natural number, and let $P(m)$ be a property pertaining to an arbitrary natural number $m$. Suppose that for each $m \ge m_0$, we have the following implication: if $P(m')$ is true for all natural numbers $m_0 \le m' < m$ , then $P(m)$ is also true. (In particular, this means that $P(m_0)$ is true, since in this case the hypothesis is vacuous.) Then we can conclude that $P(m)$ is true for all natural numbers $m \ge m0$.

*Proof 1:* (Informal) Let $Q(n)$ be the property that $P(m)$ is true for all $m_o \le m < n$. Then if $n\le m_0$, then $Q(n)$ is vacuously true. If $n = m_0{++}$, then $Q(m_0{++})$ is true because $P(m)$ is true for all natural numbers $m_0 \le m < m_0{++}$ (since $P(m_0)$ is vacuously true) and by definition of $P$, $P(m_0{++})$ is also true. Likewise, if $n = (m_0{++})++$, then $Q((m_0{++})++)$ is true becuase  $P(m)$ is true for all $m_0 \le m < (m_0{++})++$ (since $P(m_0)$ and $P(m_0{++})$ are true) and by definition of $P$, $P((m_0{++})++)$ is also true. And so it goes on and on.    


*Proof:* Let $n\in \mathbb{N}$ and let $Q(n)$ be the property that $P(m)$ is true for all $m_0 \le m < n$ for $n\ge m_0$. Using induction on $n$, for the base case $n = 0$, we want to show that $Q(0)$ is true. However, we know that $0\le m_0\ \forall\ m_0 \in \mathbb{N}$. Thus, either $0 = m_0$ or $0<m_0$ and so we split into cases. If $n = 0 < m_0$, the statement $P(m)\ \forall\ m_0\le m < n$ is vacuously true (since the hypothesis applies for $n \ge m_0$) and thus $Q(0)$ is true in this case.  For the second case, if $n = 0 =m_0$, then the statement $P(m)\ \forall\ m_0\le m < n$ is also vacuously true since there is no $m' \in \mathbb{N}$ such that $0 \le m' <0$. Hence, $Q(0)$ is true for this case and that completes the base case of the induction. 

Now suppose inductively that for some $n\ge m_0$, $Q(n)$ is true, i.e $P(m)\ \forall\ m_0\le m < n$ is true. We need to show that $Q(n{++})$ is true. 

By the definition of $P$ in the hypothesis, $P(n)$ is also true (because $Q(n)$ is true). Since $n<n++$, then $P(m)\ \forall\ m_0\le m \le n < n++$ is true so $P(m)\ \forall\ m_0\le m < n++$ is true which in turn implies that $Q(n{++})$ is true. Which closes the induction and hence we can conclude that $Q(n)\ \forall n$ is true. 

However, $Q(n)$ true implies $P(m)\ \forall\ m_0\le m<n$ is true for all $n\ge m_0$ and by the definition of $P$, $P(n)$ is true  for all $n\ge m_0$ which concludes the proof. $\square$   



**Exercise 2.2.6.** Let $n$ be a natural number, and let $P(m)$ be a property pertaining to the natural numbers such that whenever $P(m{++})$ is true, then $P(m)$
is true. Suppose that $P(n)$ is also true. Prove that $P(m)$ is true for all natural
numbers $m \le n$; this is known as the principle of *backwards induction*. (Hint:
apply induction to the variable $n$.)


*Proof:* Let $n \in \mathbb{N}$. Using induction on $n$, for the base case $n = 0$, we need to show that $P(m)$ is true $\forall\ m\le 0$. But only $0\le 0$ so we just need to show that $P(0)$ is true. Since $P(n)$ is true from the hypothesis, $P(0)$ is true and that completes the base case. 

Suppose inductively that the principle if true for $n$, i.e $P$ is such that $P(n)$ is true, and whenever $P(m{++})$ is true, $P(m)$ is true $\forall m\le n$. We have to show the principle is true for $n{++}$ i.e we need to show that $P(m)$ is true $\forall\ m\le n++$ given that $P(n{++})$ is true and given that whenever $P(m{++})$ is true, $P(m)$ is true.

Since $P(n{++})$ is true, then $P(n)$ is also true. So we have to show that $P(m)$ is true $m<n$. But from the inductive hypothesis, $P(m)$ is true $\forall$ $m\le n$ and that completes the inductive hypothesis. $\square$


**Exercise 2.3.1.** Prove Lemma 2.3.2. (Multiplication is commutative). Let $n$, $m$ be natural numbers. Then $n \times m$ = $m \times n$. 

*Proof:* First we'll present some lemmas

*Lemma1:* $m\times 0 = 0$ for any natural number $m$.

*Proof:* Using induction on $m$, we have the base case to be $0\times 0 = 0$ by definition of multiplication. Suppose inductively that $m \times 0 = 0$ is true for $m\in \mathbb{N}$, we want to show that it is also true that $m{++}\times 0 = 0$. But, $m{++}\times 0 = (m \times 0) + 0 = 0+0 = 0$. 

*Lemma2:* $n \times m{++} = (n \times m)+n$ for natural numbers $n$ and $m$.

*Proof:* Inducting on $n$ and fixing $m$, we have the base case to be $0 \times m{++} = 0 = 0+0 = (0\times m) + 0$ as desired. Now suppose inductively that $n \times m{++} = (n \times m)+n$ is true, we have to show that $n{++} \times m{++} = (n{++} \times m)+n{++}$. From the LHS we have, 

\begin{align*}
n{++} \times m{++} &= (n \times m{++})+m{++} && \text{by definition of multiplication} \\
&= ((n \times m)+n)+m{++} && \text{by the inductive hypothesis} \\
&= (((n \times m)+n){++}) + m && \textbf{Lemma 2.2.3} \\
&= (n \times m)+ n{++} + m && \textbf{Lemma 2.2.3} \\
&= (n \times m) + m + n{++} && \text{by associative law} \\
&= (n{++} \times m) + n{++} && \text{by definition of multiplication}
\end{align*}

as desired.

Now we'll show that for $n$, $m$ natural numbers, $n \times m = m \times n$.  Inducting on $n$ and keeping $m$ fixed, the base case is to show that $0 \times m= m \times 0$. However,  $0 \times m = 0$ by definition and $m \times 0 = 0$ from *Lemma1* above which completes the base case as desired. Now suppose inductively that $n\times m = m\times n$, we have to show that $n{++}\times m = m\times n{++}$. But $n{++}\times m =  (n\times m)+ m = (m\times n)+ m$ by defintion of multiplication and the inductive hypothesis. However, $(m\times n)+ m = m\times n{++}$ according to *Lemma2* above. $\square$    

**Exercise 2.3.2.** Prove Lemma 2.3.3. (Positive natural numbers have no zero divisors). Let $n$, $m$ be natural numbers. Then $n \times m = 0$ if and only if at least one of $n$, $m$ is equal to zero. In particular, if $n$ and $m$ are both positive, then $nm$ is also positive.


*Proof:*
We'll prove the second statement first as a lemma.

*Lemma1:* If $n$ and $m$ are both positive, then $nm$ is also positive. 

*Proof:* Let $n,\ m$ be positive numbers. Using strong induction on $n$ while keeping $m$ fixed. For the base case $n = 1>0$, we want to show that $1\times m$ is positive. But $1\times m = 0{++}\times m = (0\times m) +m = m$ which is postive. Suppose that $nm$ is positive for all $x$ such that $1\le x < n{++}$, we want to show it is true for $n{++}$. But we know that $n{++}\times m = (n\times m) + m$ which is positive since $n\times m$ is positive (from the inductive hypothesis) and since addition of two positive numbers is also a positive number. Hence, $nm$ is positive for all $n,\ m \ge 1$   


Now we'll show that for $n$, $m$ natural numbers, $n \times m = 0$ if and only if at least one of $n$, $m$ is equal to zero. First we'll show that $n\times m = 0$ implies that at least one of $n,\ m$ is zero. Suppose for the sake of contradiction that there exists $n,\ m \ne0$ such that $n\times m = 0$, then according to *Lemma1*, there is a contradiction so at least one of $n, \ m$ is zero. 

Next we'll show that if at least one of $n,\ m$ is zero, then $n\times m= 0$. Either one of $n,\ m$ is zero or both of $n,\ m$ are zero so we split into cases. If both $n,\ m$ are zero, then $n\times m = 0\times 0= 0$ as desired. If one of $n,\ m$ is zero, either $n = 0$ and $m \ne 0$ or $n\ne 0$ and $m = 0$ so we split into cases. If $n = 0$ and $m \ne 0$, then $n\times m = 0\times m = 0$ by definiton. Likewise, if  $n\ne 0$ and $m = 0$, then $n\times m = n \times 0 =0$ by *Lemma1* of **Exercise 2.3.1.**. $\square$   



**Exercise 2.3.3.** Prove Proposition 2.3.5. (Multiplication is associative). For any natural numbers $a$, $b$, $c$, we have $(a \times b) \times c = a \times (b \times c)$.

*Proof*: Let$a$, $b$, $c$ be natural numbers. Inducting on $c$ while keeping others fixed. We have to show for the base case that $(a\times b)\times 0 = a\times (b\times0)$. Both the RHS and LHS equal to zero as desired. Supose inductively that $(a\times b)\times c = a\times (b\times c)$, we have to show that $(a\times b)\times c{++} = a\times (b\times c{++})$. But 
\begin{align*}
(a\times b)\times c{++} &= \left[(a\times b)\times c\right] + (a\times b) && \text{by definition of $\times$} \\
&= \left[a\times (b\times c)\right] + (a\times b) && \text{by the inductive hypothesis} \\
&= a(bc) + ab  &&  \\
&= a[bc+b]  && \text{by distributive law} \\
&= a\times(b\times c{++})&& \text{by definition} 
\end{align*}

as desired and so we close the induction. $\square$   
**Exercise 2.3.4.** Prove the identity $(a + b)^2 = a^2 + 2ab + b^2$ for all natural numbers $a$, $b$.

*Proof:* We have that 

\begin{align*}
(a+b)^2 &= (a+b)(a+b) && \text{by definition of exponentiation} \\
&= a(a+b) + b(a+b) && \text{by the distributive law} \\
&= aa + ab + ba + bb && \text{by the distributive law} \\
&= a^2 + ab + ab + b^2 && \text{by definition of exponentiation, and commutativity of $\times$} \\
&= a^2 + a(b + b) + b^2 && \text{by distributive law} \\
&= a^2 + a((1\times b) + b) + b^2 && \text{by definition of multiplication} \\
&= a^2 + a(1{++}\times b) + b^2 && \text{by definition of multiplication} \\
&= a^2 + a(2b) + b^2 && \text{by definition of increment} \\
&= a^2 + 2ab + b^2 && \hfill \square
\end{align*}

**Exercise 2.3.5.** Prove Proposition 2.3.9. (Euclidean algorithm). Let $n$ be a natural number, and let $q$ be a positive number. Then there exist natural numbers $m$, $r$ such that $0 \le r < q$ and $n = mq + r$. (*Hint*: fix $q$ and induct on $n$.)

*Proof:* Let $n \in \mathbb{N}$. Inducting on $n$ and fixing $q$, for the base case $n = 0$, we need to show that for some $q\in\mathbb{N+}$ there exist $m$, $r$ $\in \mathbb{N}$ such that $0 = mq+r$. But $0 = 0+0$ and we also know that $0\times q = 0\  \forall q\ \in\ \mathbb{N+}$ so $0 = 0\times q + 0$. Taking $m = 0$ and $r = 0$ completes the proof of the base case. 


Suppose inductively that the algorithm is true for $n$, i.e for some $q \in \mathbb{N+}$ there exist  $m$, $r$ $\in \mathbb{N}$ such that $n = mq+r$ with $0 \le r < q$. We have to show the principle is true for $n{++}$ i.e we need to show that for some $k \in \mathbb{N+}$, there exist $a$, $b$ $\in \mathbb{N}$ such that $n{++} = ak+b$ with $0\le b < k$. But $n{++} = n + 1 = (mq + r) + 1 = mq + r+1 = mq + r{++}$. Since $r<q$, then  $r++ \le q$ which means that either $r{++}<q$ or $r{++} = q$. If $r{++} < q$, then taking $a = m$, $b = r{++}$ and $k = q$ completes the case as desired. On the otherhand, if $r{++} = q$, then 
$$n{++} = mq + q = (m{++})q = (m{++})q + 0.$$

Taking $a = m{++}$, $b = 0$, $q = k$ completes the proof. $\square$

# Chapter 3

**Exercise 3.1.1.** Show that the definition of equality in Definition 3.1.4 is reflexive, symmetric, and transitive.

**Reflexive:** We need to show that for an arbitrary set $A$, $A = A$.

*Proof:* Let $A$ be an arbitrary set and let $x$ be an arbitrary object in $A$, i.e $x\in A$. Then it is trivially true that $A = A$ because any arbitrary $x$ in $A$ is an element of $A$ so by **Definition 3.1.4**(Equality of Sets), $A = A$ and consequently equality of sets is reflexive. 

**Symmetric:** Given two sets $A$ and $B$. If $A = B$, $B = A$.

*Proof:* Let $A$ and $B$ be arbitrary sets such that $A = B$. Then all the elements of $A$ are in $B$ and all the elements of $B$ are in $A$. So $B = A$ for the same reasons by **Definition 3.1.4**(Equality of Sets). Thus, equality of sets is symmetric.

**Transitive:** Given 3 sets $A$, $B$ and $C$. If $A = B$ and $B = C$, then $A = C$.

*Proof:* Let $A$, $B$  and $C$ be arbitrary sets such that $A = B$ and $B = C$. Let $x$ be an arbitrary object in $A$, then $x\in B$ and since $B=C$, $x\in C$. Likewise, let $y\in C$, then  $y\in B$ and since $A = B$, $y\in A$. So all the elements of A are in $C$ and vice versa so $A = C$. Thus, equality of sets is transitive.

**Exercise 3.1.2.** Using only Definition 3.1.4, Axiom 3.1, Axiom 3.2, and Axiom 3.3, prove that the sets  $\{\emptyset\}$, $\{\{\emptyset\}\}$ and $\{\emptyset, \{\emptyset\} \}$ are all distinct (i.e., no two of them are equal to each other). 

*Proof:* Considering $\emptyset$ and $\{\emptyset\}$. By Axiom 3.2, $x\notin \emptyset$ for all $x$. However, $\emptyset \in \{\emptyset\}$ and since $\emptyset \notin \emptyset$, $\emptyset \neq \{\emptyset\}$. Furthermore, $\emptyset \neq \{\{\emptyset\}\}$ becuase $\{\emptyset\} \in \{\{\emptyset\}\}$ but $\{\emptyset\}\notin \emptyset$. Likewise, $\{\emptyset\} \neq \{\{\emptyset\}\}$ because $\{\emptyset\} \in \{\{\emptyset\}\}$ but $\{\emptyset\} \notin \{\emptyset\}$. Also $\{\{\emptyset\}\} \neq \{\emptyset, \{\emptyset\}\}$ because $\emptyset\notin \{\{\emptyset\}\}$ but $\emptyset\in \{\emptyset, \{\emptyset\}\}$

**Exercise 3.1.3** Prove the remaining claims in Lemma 3.1.13. 

*Claim:* If $a$ and $b$ are objects, then $\{a, b\}$ = $\{a\} \cup \{b\}$.

*Proof*: Let $x\in\{a,b\}$, then by Axiom 3.3, $x = a$ or $x = b$. If $x = a$, then $x\in \{a\} \cup \{b\}$ (since $x\in\{a\}$). Likewise, if $x = b$, then  $x\in \{a\} \cup \{b\}$. So therefore, $x\in\{a,b\}$ implies $x\in \{a\} \cup \{b\}$. 

On the contrary, let $y\in \{a\} \cup \{b\}$, then by Axiom 3.4, $y\in\{a\}$ or $y\in\{b\}$ so we split into cases. If $y\in\{a\}$, then by Axiom 3.3, $y = a$ and since $y = a\in\{a,b\}$, $y\in\{a,b\}$. Also, if $y\in\{b\}$, then $y\in\{a,b\}$ following the same line of argument. So in both cases, if $y\in \{a\} \cup \{b\}$, then $y\in\{a,b\}$.

Consequently, $\{a, b\}$ = $\{a\} \cup \{b\}$. 

*Claim:* $A\cup B = B\cup A$.

*Proof: * Let $x$ be an object such that $x\in a\cup B$. Then by Axiom 3.4, $x\in A$ or $x\in B$. If $x\in A$, then $x\in B\cup A$ ($B\cup A \iff x\in B \text{ or } x\in A$) and if  If $x\in B$, then $x\in B\cup A$. Consequently, if $x\in A\cup B$, then $x\in B\cup A$. Following the ssame argument, if $y\in B\cup A$, then $y\in A\cup B$.

Since all the objects of $A\cup B$ is also in $B\cup A$ and vice versa, then $A\cup B = B\cup A$.

**Exercise 3.1.4** Prove the remaining claims in Proposition 3.1.18.

*Claim:* Let A, B be sets. If $A\subseteq B$ and $B \subseteq A$, then $A = B$.

*Proof:* Let A and B be sets such that $A\subseteq B$ and $B \subseteq A$. Since $A\subseteq B$, if $x\in A$ then $x\in B$ by Definition Definition 3.1.15 (Subsets). Likewise, if $y\in B$, then $y\in A$ (because $B \subseteq A$). Since all the element of $A$ are in $B$ and all the elements of $B$ are in $A$, then $A = B$.


*Claim:* If $A \subsetneq  B$ and $B \subsetneq C$ then $A \subsetneq C$. 

*Proof:* Let $A$, $B$, and $C$ be sets such that $A \subsetneq  B$ and $B \subsetneq C$. By definition 3.1.15, we have to show that $A \subseteq C$ and $A\neq C$. Let $x$ be any arbitrary object in $A$. Then $x\in B$ and $x\in C$ (since $A \subsetneq  B$ and $B \subsetneq C$). Consequently, $A \subseteq C$. Now we have to show that $A \neq C$. Since $A\subsetneq B$ ($A \subseteq B$ and $A \ne B$), there exist at lease one object $y\in B$ such that, $y\notin A$. However, $y\in B$ implies $y\in C$ (since $B\subsetneq C$). Since $y\in C$ and $y\notin A$, $A \ne C$ and that completes the proof. 


**Exercise 3.1.5** Let A, B be sets. Show that the three statements $A \subseteq B$, $A \cup B = B$, $A \cap B = A$ are logically equivalent (any one of them implies the other two).

*Claim 1:* If $A\subseteq B$, then $A\cup B = B$. 

*Proof:* Let A and B be arbitrary sets such that $A\subseteq B$ and let $x\in A\cup B$, then either $x\in A$ or $x\in B$ so we split into cases. If $x\in B$, then we're done as required. On the contrary. if $x\in A$, then $x\in B$ also (since $A \subseteq B$). So in both cases, if $x\in A\cup B$, then $x\in B$.

Now let $y\in B$, then by Axiom 3.4 (Pairwise union), $y\in A\cup B$. Since all the elements of $A\cup B$ are in $B$ and vice versa whenever $A\subseteq B$, then $A\cup B = B$ whenever $A\subseteq B$.

*Claim 2:* If $A\subseteq B$, then $A\cap B = A$. 

*Proof:* Let A and B be arbitrary sets such that $A\subseteq B$ and let $x\in A\cap B$, then by Definition 3.1.23 (Intersections) $x\in A$. Now let $y\in A$, then  $y\in B$ also (since $A\subseteq B$) so $y\in A\cap B$. Since all the elements of $A\cap B$ are in $A$ and vice versa whenever $A\subseteq B$, then $A\cap B = A$ whenever $A\subseteq B$.

*Claim 3:* If $A\cup B = B$, then $A\subseteq B$

*Claim 4:* If $A\cup B = B$, then $A\cap B = A$

*Claim 5:* If $A\cap B = A$, then $A\subseteq B$

*Claim 6:* If $A\cap B = A$, then $A\cup B = B$

**Exercise 3.1.6** Prove Proposition 3.1.28. (Sets form a boolean algebra). Let $A$, $B$, $C$ be sets,
and let $X$ be a set containing $A$, $B$, $C$ as subsets.

*Claim (a):* (Minimal element) We have $A \cup \emptyset = A$ and $A \cap \emptyset = \emptyset$.

*Proof:* For $A \cup \emptyset = A$, we have to show that any object $x\in A$ is also in $A \cup \emptyset$ and vice versa. Let $x$ be any arbitrary object in $A$. Then by Axiom 3.4 (Pairwise Union), $x\in A\cup \emptyset$. Likewise if $x\in A\cup \emptyset$, thhen $x\in A$ or $x\in \emptyset$. However, for all $x$, $x\notin \emptyset$ so therefore, $x\in A$. Since $x\in A$ implies $x\in A\cup \emptyset$ and vice versa, $A\cup \emptyset = A$ 

For $A \cap \emptyset = \emptyset$. Let $x\in A \cap \emptyset$, then by Definition 3.1.23, $x\in A$ and $x\in \emptyset$. However, $x\notin\emptyset$ for all $x$ so the statements $x\in A \cap \emptyset \implies x\in\emptyset$ is vacuously true. Likewise, the statement $x\in \emptyset \implies x\in A\cap \emptyset$ is vacuously true. So $A\cap\emptyset = \emptyset$.

*Claim (b):* (Maximal element) We have $A \cup X = X$and $A \cap X = A$.

*Proof:* Let $m\in A\cup X$. Then either $m\in A$ or $m\in X$. If $m\in A$, then $m\in X$ since $A\subseteq X$.\ so in both cases, $m\in X$. Likewise, let $n\in X$, then $n\in A\cup X$. So $A \cup X = X$.

For $A \cap X = A$, let $y\in A\cap X$. Then $y\in A$. Likewise, if $y\in A$, then $y\in X$ since $A\subseteq X$ so $y\in A\cap X$. Therefore, $A \cap X = A$.

*Claim (c):* (Identity) We have $A \cap A = A$ and $A \cup A = A$.

*Proof:* Let $x\in A\cap A$, then $x\in A$. Likewise, if $x\in A$, then $x\in A\cap A$ so $A\cap A = A$. 

For $A \cup A = A$, let $y\in A\cup A$, then $y\in A$ and if $y\in A$, then $y\in A\cup A$ so $A \cup A = A$.

*Proof2: * Since $A\subseteq A$, using principle of maximal element (i.e, taking $X$ to be $A$), then $A\cap X = A$ implies $A\cap A = A$ and $A\cup X = X$ implies $A\cup A = A$.

*Claim (d):* (Commutativity) We have $A \cup B = B \cup A$ and $A \cap B = B \cap A$

*Proof:* For $A \cup B = B \cup A$, see Exercise 3.1.3. 

*Claim (e):* (Associativity) We have $(A\cup B)\cup C = A\cup(B\cup C)$ and $(A\cap B)\cap C = A \cap (B \cap C)$.
*Proof:* For $(A\cup B)\cup C = A\cup(B\cup C)$, see Lemma 3.1.13. For $(A\cap B)\cap C = A \cap (B \cap C)$, let $x\in (A\cap B)\cap C$. Then $x\in A\cap B$ and $x\in C$. Now $x\in A\cap B$ implies $x\in A$ and $x\in B$. Since $x\in B$ and $x\in C$, then $x\in B\cap C$. Furthermore, since $x\in A$, then $x\in A \cap (B \cap C)$ so therefore, $x \in (A\cap B)\cap C \implies x\in A\cap (B\cap C)$.  Following similar argument, we have that $y\in  A \cap (B \cap C) \implies y\in (A\cap B)\cap C$.

*Claim (f):* (Distributivity) We have $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$ and $A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$.

*Proof:* For $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$. Let $x\in A \cap (B \cup C)$. Then $x\in A$ and $x\in B\cup C$. $x\in B\cup C$ implies that $x\in B$ or $x\in C$. If $x\in B$, then $x\in A\cap B$ and so $x\in A \cap B) \cup (A \cap C)$. On the other hand, if $x\in C$, then $x\in A\cap C$ so $x\in A \cap B) \cup (A \cap C)$. In both cases, $x\in A \cap (B \cup C) \implies x\in (A \cap B) \cup (A \cap C)$.

Likewise, let $y\in (A \cap B) \cup (A \cap C)$, then either $y \in (A\cap B) \text{ or } y\in A\cap C$ so we split into cases. If $y\in (A\cap B)$, then $y\in A$ and $y\in B$. Now $y\in B$ implies $y\in B\cup C$ and since $y\in A$, then $y\in A\cap(B\cup C)$. On the other hand, if $y\in A \cap C$, then $y\in A$ and $y\in C$. $y\in C \implies y\in B\cup C$ and since $y\in A$, then $y\in A\cap(B\cup C)$. So in both cases $y\in (A \cap B) \cup (A \cap C) \implies y\in A \cap (B \cup C)$.

Since any arbitrary object in $A \cap (B \cup C)$ is also in $(A \cap B) \cup (A \cap C)$ and vice versa, then $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$

The second claim $A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$ can also be proven following similar lines of arguments as the one above.....


*Claim (g):* (Partition) We have $A \cup (X\setminus A) = X \text{ and } A \cap (X\setminus A) = \emptyset$

*Proof:* For $A \cup (X\setminus A) = X$. Let $x\in A \cup (X\setminus A)$, then either $x\in A$ or $x\in X\setminus A$ so we split into cases. If $x\in A$, then $x\in X$ since $A\subseteq X$. On the other hand, if $x\in X\setminus A$, then $x$ is such that $x\in X$ and $x\notin A$ in which case $x\in X$. So for both cases, $x\in A\cup(X\setminus A) \implies x\in X$. 

Now we have to show that $x\in X \implies x\in A\cup(X\setminus A)$. Let $x$ be any arbitrary object in $X$, since $A\subseteq X$, either $x\in A$ or $x\notin A$. So we split into cases. If $x\in A$, then $x\in A\cup(X\setminus A)$. On the other hand, if $x\notin A$, then $x\in X\setminus A$ and so $x\in A \cup (X\setminus A)$. So in both cases, $x\in X \implies x\in A\cup(X\setminus A)$.

Since all the elements of $X$ are in $A\cup(X\setminus A)$ and vice versa, then $A \cup (X\setminus A) = X$. $\square$. 

For the claim $A \cap (X\setminus A) = \emptyset$. Suppose for the case of contradiction that there exists an object $x$ such that $x\in A \cap (X\setminus A)$. Then, $x\in A$ and $x\in X\setminus A$. However, $x\in X\setminus A$ implies $x\in A$ which is a contradiction. So for all objects $x$, $x\notin A\cap(X\setminus A)$. Also by Axiom 3.2 (Empty set), we have $x\notin \emptyset$ for all $x$. Thus, $x\in A\cap(X\setminus A) \iff x\in \emptyset$ and so $A \cap (X\setminus A) = \emptyset$. $\square$

*Claim (h):* De Morgan laws) We have $X\setminus(A \cup B) = (X\setminus A) \cap (X\setminus B)$ and
$X\setminus(A \cap B) = (X\setminus A) \cup (X\setminus B)$.

*Proof:* For the claim $X\setminus(A \cup B) = (X\setminus A) \cap (X\setminus B)$. Let $x\in X\setminus(A \cup B)$, then $x\in X$ and $x\notin A\cup B$ i.e $x\notin A$ and $x\notin B$. Therefore, $x\in X\setminus A$ and $x\in X\setminus B$ (because $x \in X$, $x\notin A$ and $x\notin B$) and consequently, $x\in (X\setminus A) \cap (X\setminus B)$. So $x\in X\setminus(A \cup B) \implies  (X\setminus A) \cap (X\setminus B)$. 

Now we have to show that $y\in (X\setminus A) \cap (X\setminus B) \implies y\in X\setminus(A \cup B)$. Let $y$ be any arbitrary object in $(X\setminus A) \cap (X\setminus B)$. Then $y \in (X\setminus A)$ and $y\in ( X\setminus B)$ so $y\notin A$ and $y\notin B$ and consequently, $y\notin A\cup B$ (because $y\notin A\cup B \iff y\notin A$ and $y\notin B$). Since $y\in X$ and $y\notin A\cup B$, then $y\in X\setminus (A\cup B)$. So $y\in (X\setminus A) \cap (X\setminus B) \implies y\in X\setminus(A \cup B)$. 

Since any arbitrary element of $X\setminus(A \cup B)$ is in $(X\setminus A) \cap (X\setminus B)$ and vice versa, then $X\setminus(A \cup B) = (X\setminus A) \cap (X\setminus B)$. $\square$ 

For the claim $X\setminus(A \cap B) = (X\setminus A) \cup (X\setminus B)$. Let $x\in  X\setminus(A \cap B)$. Then $x\in X$ and $x\notin A\cap B$ i.e $x\notin A$ or $x\notin B$ sp we split into cases.  If $x\notin A$, then $x\in X\setminus A$ and consequently, $x\in (X\setminus A) \cup (X\setminus B)$. On the other hand, if $x\notin B$, then $x\in X\setminus B$ so $x\in (X\setminus A) \cup (X\setminus B)$ again. So in both cases, $x\in X\setminus(A \cap B) \implies x\in (X\setminus A) \cup (X\setminus B)$.

Now we show that $y\in (X\setminus A) \cup (X\setminus B) \implies y\in X\setminus(A \cap B)$. Let $y$ be an arbitrary object in $(X\setminus A) \cup (X\setminus B)$. Then $y\in (X\setminus A)$ or $y\in (X\setminus B)$ so we split into cases. If $y\in (X\setminus A)$, then $y\in X$ and $y\notin A$. Since $y\notin A$, then $y\notin A\cap B$ so $y \in X\setminus (A\cap B)$. On the other hand if $y\in (X\setminus B)$, then $y\in X$, $y\notin B$ so $y\notin A\cap B$ and consequently, $y\in X\setminus (A\cap B)$. So in both cases, $y\in (X\setminus A) \cup (X\setminus B) \implies y\in X\setminus(A \cap B)$.

Since all the elements of $X\setminus(A \cap B)$ are in $(X\setminus A) \cup (X\setminus B)$ and vice versa, then $X\setminus(A \cap B) = (X\setminus A) \cup (X\setminus B)$. $\square$

**Exercise 3.1.7** Let $A$, $B$, $C$ be sets. Show that $A \cap B \subseteq A$ and $A \cap B \subseteq B$. Furthermore, show that $C\subseteq A$ and $C \subseteq B$ if and only if $C \subseteq A \cap B$. In a similar spirit, show that $A \subseteq A \cup B$ and $B \subseteq A \cup B$, and furthermore that  $A \subseteq C$ and $B \subseteq C$ if and only if $A \cup B \subseteq C$.

*Claim (1):* Show that $A\cap B\subseteq A$.

*Proof:* We want to show that any $x\in A\cap B$ is also in $A$, i.e  $x\in A\cap B \implies x\in A$. Let $x \in A\cap B$, then $x\in A$ and $x\in B$. Thus, every element of $A\cap B$ is also in $A$.

*Claim (2):* Show that $A\cap B\subseteq B$.

*Proof:* Following the same argumne t above, we see that every element of $A\cap B$ is also in $B$.

*Claim (3):* Show that $C \subseteq A$ and $C\subseteq B$ iff $C\subseteq A\cap B$.

*Proof:* First we show that $C \subseteq A, \ C\subseteq B\implies C\subseteq A\cap B$. Take any arbitrary $x\in C$. Then $x\in A$ and $x\in B$ and consequently, $x\in A\cap B$ so any arbitrary element of $C$ is also in $A\cap B$. Now we show the reverse implication, i.e $C\subseteq A\cap B \implies C \subseteq A, \ C\subseteq B$. Pick any arbitrary element in $C$, since $C\subseteq A\cap B$, $x\in A\cap B$ and consequently, $X\in A$ and $x\in B$. So any arbitrary element in $C$, $x\in C$, is also an element of $A$ and $B$.

*The other claims can be shown easily following similar arguments to the ones above*

**Exercise 3.1.8** Let $A,\ B$ be sets. Prove the absorption laws $A \cap (A \cup B) = A$ and $A \cup (A \cap B) = A$.

*Claim (1):* $A \cap (A \cup B) = A$

*Proof:* Let $x$ be an arbitrary element in $A \cap (A \cup B)$. Then $x\in A$ and $x\in (A\cup B)$. So $x\in A \cap (A \cup B) \implies x\in A$. Furthermore, let $y\in A$, then $y\in A\cup B$. Since $y\in A$, and $y\in A\cup B$, then $y\in A\cap (A\cup B)$ so $y\in A \implies A \cap (A \cup B)$. Consequently, $A \cap (A \cup B) = A$. 

*Claim (2):* $A \cup (A \cap B) = A$

*Proof:* Let $x$ be an arbitrary element in $A$, then $x\in A \cup (A \cap B)$ so $x\in A \implies x\in x\in A \cup (A \cap B)$. Likewise, let $y\in A\cup(A\cap B)$. Either $y\in A$ or $y\in A\cap B$. If $y\in A$, then $y\in A\cup(A\cap B) \implies y\in A$. On the other hand, if $y\in A\cap B$, then $y\in A$ and $y\in B$ so $y\in A\cup(A\cap B) \implies y\in A$ too. Since $x\in A \implies x\in x\in A \cup (A \cap B)$ and $y\in A\cup(A\cap B) \implies y\in A$, $A \cup (A \cap B) = A$.   

**Exercise 3.1.9** Let $A,\ B,\ X$ be sets such that $A \cup B = X$ and $A \cap B = \emptyset$. Show that $A = X\setminus B$ and $B = X\setminus A$.

*Claim (1):* $A = X\setminus B$

*Proof:* Let $x\in A$, then $x\in A\cup B$ and $x\in A$. Since $x\in A$ and $A\cap B = \emptyset$, then $x\notin B$. Since $x\in X$ and $x\notin B$, then $x\in X\setminus B$. Likewise let $y\in x\setminus B$, then $y\in X$ and $y\notin B$. Since $A\cup B = X$, then $y\in A\cup B$. But $y\in A\cup B \implies y\in A \text{ or } y\in B$. But we know already that $y\notin B$ so $y\in A$. Since $x\in A \implies x\in X\setminus B$ and $y\in X\setminus B \implies y\in A$, $A = X\setminus B$


*Claim (2): can be shown following the same argument*.

**Exercise 3.1.10** Let $A$ and $B$ be sets. Show that the three sets $A\setminus B$, $A \cap B$, and $B\setminus A$ are disjoint, and that their union is $A \cup B$. 

*Claim (1):* $(A\setminus B) \cap (A\cap B) \cap (B\setminus A) = \emptyset$.

*Proof:* Suppose for the sake of contradiction that $(A\setminus B) \cap (A\cap B) \cap (B\setminus A)$ is not empty. Then by **Lemma 3.1.6**, there exist an object $x$ such that $x\in (A\setminus B) \cap (A\cap B) \cap (B\setminus A)$. Then $x\in (A\setminus B)$ and that implies $x\in A$ and $x\notin B$. However, $x\in (A\setminus B) \cap (A\cap B) \cap (B\setminus A)$ also implies that $x\in A\cap B$ which in turn implies that $x\in B$. So we have $x\in B$ and $x\notin B$ which is a contradiction. So therefore, there is no $x$ such that $x\in (A\setminus B) \cap (A\cap B) \cap (B\setminus A)$ and that means $(A\setminus B) \cap (A\cap B) \cap (B\setminus A) = \emptyset$.  

*Claim(2):* $(A\setminus B) \cup (A\cap B) \cup (B\setminus A) = A\cup B$

*Proof:* Let $x\in (A\setminus B) \cup (A\cap B) \cup (B\setminus A)$. Then $x$ is an element of either of the three sets so we break into cases. If $x\in A\setminus B$, then $x\in A$ and $x\notin B$ so $x\in A\cup B$. Likewise, if $x\in A\cap B$, then $x\in A\cup B$. On the other hand, if $x\in B\setminus A$, then $x\in B$ and $x\in A\cup B$. So for all three possible cases,  $x\in (A\setminus B) \cup (A\cap B) \cup (B\setminus A)\implies x\in A\cup B$. Now have have to show that $x\in A\cup B \implies x\in (A\setminus B) \cup (A\cap B) \cup (B\setminus A)$. Let $y\in A\cup B$, then either $y\in A$ or $y\in B$ so we break into cases. For the first case, if $y\in A$, then either $y\in B$ or $y\notin B$. If $y\in B$, then $y\in A\cap B$ so $y\in (A\setminus B) \cup (A\cap B) \cup (B\setminus A)$. On the other hand, if $y\notin B$, then $y\in A\setminus B$ so $y\in (A\setminus B) \cup (A\cap B) \cup (B\setminus A)$ also. For the second case, we can follow the same argument to arrive at $y\in (A\setminus B) \cup (A\cap B) \cup (B\setminus A)$ again. Since, $x\in (A\setminus B) \cup (A\cap B) \cup (B\setminus A)\implies x\in A\cup B$ and $x\in A\cup B \implies x\in (A\setminus B) \cup (A\cap B) \cup (B\setminus A)$,
$(A\setminus B) \cup (A\cap B) \cup (B\setminus A) = A\cup B$.

**Exercise 3.1.11** Show that the axiom of replacement implies the axiom of
specification. 

*Proof* Let $A$ be a set and suppose we have a property $P$ for each $x \in A$, so we want to show $\{x \in A : P(x)\}$ exists using the axiom of replacement. For each object $x\in A$, define the property $Q(x, y)$ to be that $y = x$ and $P(x)$ is true. Then by the axiom of replacement, the set $\{y:Q(x,y)\ is\ true \ for\ some\ x\in A\}$ exists. Now let $z\in \{y:Q(x,y)\ is\ true \ for\ some\ x\in A\}$, then $Q(x,z)$ is true and by definition of $Q$, we have that $z = x$, $z\in A$ and $P(z)$ is true which leads to the set we're looking to define in the axiom of specification. i.e 

$z\in \{y:Q(x,y)\ is\ true \ for\ some\ x\in A\} \implies z\in \{x \in A : P(x)\}$

## 3.2

**Exercise 3.2.1**

**Exercise 3.2.2**

**Exercise 3.2.3**


## 3.3

**Exercise 3.3.1** Show that the definition of equality in Definition 3.3.7 is reflexive, symmetric, and transitive. Also verify the substitution property: if $f, \tilde{f}: X \mapsto Y$ and $g, \tilde{g}: Y\mapsto Z$ are functions such that $f = \tilde{f}$ and $g = \tilde{g}$, then $g \circ f = \tilde{g} \circ \tilde{f}$. 

*Reflexive axiom:*  Given any object $x$, we have $x = x$.

*Proof:* Let $f: X \mapsto Y$ be a function.  Clearly the domain and range of $f$ does not change in this case and $f(x) = f(x)\ \forall x\in X$ so therefore, therefore $f = f$ and the definition of equality in Definition 3.3.7 is reflexive. $\square$

*Symmetric axiom:* Given any two objects $x$ and $y$ of the same type, if $x = y$, then $y = x$.

*Proof:* Let $f:X\mapsto Y$ and $g:X\mapsto Y$ be two functions with the same domain and range such that $f = g$. Then by Definition 3.3.7, $f(x) = g(x) \ \ \forall\ x\in X$. We have to show that $g = f$. Since $g$ and $f$ have the same domain and range, we just need to show that $g(x) = f(x) \ \forall x\in X$. However, $f(x) = g(x)\ \forall x\in X$ so $g(x) = f(x)\ \forall x\in X$. Consequently, $g = f$ and Definition 3.3.7 obeys the symmetric axiom. $\square$

*Transitivity axiom:* Given any three object $x$, $y$ and $z$ of the same type, if $x = y$ and $y = z$, then $x = z$.

*Proof:* Let $f,g,h$ be functions with domain $X$ and range $Y$ such that $f = g$ and $g =h$. We want to show that $f = h$. By Definition 3.3.7, $f = g \implies f(x) = g(x) \ \forall x\in X$ and $g = h \implies g(x) = h(x) \ \forall x\in X$. So we have that $f(x) = g(x) = h(x) \ \forall x\in X$. So $f(x) = h(x) \ \forall x\in X$ and so $f = h$. $\square$


*Substitution axiom:* Given any two object $x$ and $y$ of the same type, if $x = y$, then $f(x) = f(y)$ for all functions or operations $f$.

*Substitution property for functions:* If $f, \tilde{f}: X\mapsto Y$ and $g, \tilde{g}: Y\mapsto Z$ are functions such that $f = \tilde{f}$ and $g = \tilde{g}$. Then $g\circ f = \tilde{g} \circ \tilde{f}$.

*Proof:* By Defintion 3.3.10, $g\circ f = g(f(x))$. However, $f = \tilde{f}$ implies that $f(x) = \tilde{f}(x) \ \forall x\in X$ so $g\circ f = g(f(x)) = g(\tilde{f}(x))$. Likewise, $g = \tilde{g}$ so $g\circ f = g(f(x)) = \tilde{g}(\tilde{f}(x)) =  \tilde{g} \circ \tilde{f}$ by Defintion 3.3.10. $\square$


**Exercise 3.3.2** Let $f: X \mapsto Y$ and $g:Y\mapsto Z$ be functions. Show that if $f$
and $g$ are both injective, then so is $g \circ f$ ; similarly, show that if $f$ and $g$ are both surjective, then so is $g \circ f$.

*Claim (1):* Show that if $f$ and $g$ are both injective, then so is $g \circ f$.

*Proof (a):* Let $x, x' \in X$ such that $x \ne x'$. We have to show that $g\circ f(x) \ne g\circ f(x')$. Since $f$ in injective and $x \ne x'$, then $f(x) \ne f(x')$. Furthermore, since $g$ is injective, $g(f(x)) \ne g(f(x'))$ (because $f(x) \ne f(x')$). So $g\circ f(x) \ne g\circ f(x')$ and that completes the proof. $\square$ 



*Claim (2):* Show that if $f$ and $g$ are both surjective, then so is $g \circ f$.

*Proof:* Since $g$ is surjective, for all $z\in Z$, there exists $y\in Y$ such that $g(y) = Z$. However, $f$ is also surjective so for all $y\in Y$, there exists $x\in X$ such that $f(x) = y$. So for all $z\in Z$, there exists $y\in Y$ and for all such $y$, there exists $x\in X$ such that $g(f(x)) = z$. So therefore, $g\circ f$ is also surjective. $\square$ 

**Exercise 3.3.3** Exercise 3.3.3. When is the empty function injective? surjective? bijective?

The empty function is injective for any range (vacuously true). Surjective when the range is empty and bijective when the range is empty. $\square$ 

**Exercise 3.3.4** Let $f : X \mapsto Y$ , $\tilde{f} : X \mapsto Y$ , $g:Y\mapsto Z$, and $\tilde{g}:Y\mapsto Z$ be functions. Show that if $g \circ f = g \circ \tilde{f}$  and $g$ is injective, then $f = \tilde{f}$. Is the same statement true if $g$ is not injective? Show that if $g \circ f = \tilde{g} \circ f$ and $f$ is surjective, then $g = \tilde{g}$.  Is the same statement true if $f$ is not surjective? 

*Proof:* Since $g \circ f = g \circ \tilde{f}$, then $g(f(x)) = g(\tilde{f}(x))$. Add in the fact that $g$ is injective, then $f(x) = \tilde{f}(x)$. Since $f$ and  $\tilde{f}$ have the same domain and range and $f(x) = \tilde{f}(x)\ \forall x \in X$, then $f = \tilde{f}$. The statement wouldn't be true if $g$ wasn't injective because we can't guarantee that the inputs of $g$ are the same if its outputs are equal, i.e, we can't be sure that  $f(x) = \tilde{f}(x)$. 

Likewise, since $g \circ f = \tilde{g} \circ f$ and $f$ is surjective, then all $y \in Y$ are produced by applying $f$ to some $x\in X$, so therefore $g(f(x)) = \tilde{g}(f(x))$ implies that $g(y) = \tilde{g}(y)$ for all $y\in Y$, and so $g = \tilde{g}$ since they have the same domain and range. The statement wouldn't be true if $f$ is not surjective, because then  there exists $y\in Y$ such that $y \neq f(x)$. Consequently we can't guarantee that $g(f(x)) = \tilde{g}(f(x))$ implies $g(y) = \tilde{g}(y)$ because there are some $y$ (inputs of $g$) which are not images of $f$ and our assumption of equality of composition (that $g(f(x)) = \tilde{g}(f(x))$) only works on images of $f$. $\square$ 

**Exercise 3.3.5** Let $f : X \mapsto Y$ and $g : Y \mapsto Z$ be functions. Show that if $g \circ f$
is injective, then $f$ must be injective. Is it true that $g$ must also be injective? Show that if $g \circ f$ is surjective, then $g$ must be surjective. Is it true that $f$ must also be surjective?

*Claim (1):* Show that if $g \circ f$ is injective, then $f$ must be injective. Is it true that $g$ must also be injective?

*Proof:*  Let $x, \ x' \in X$ such that $f(x) = f(x')$. We have to show that $x = x'$. Since $f(x) = f(x')$, then $g(f(x)) = g(f(x'))$ (since $g$ is a function). Now $g(f(x)) = g(f(x'))$ implies $(g\circ f) (x)= (g\circ f)(x')$ and since $(g\circ f)$ is injective, then $x = x'$. Since $f(x) = f(x')$ implies that $x = x'$, then $f$ is injective and $g$ doesn't have to be injective.

*Claim (2):* Show that if $g \circ f$ is surjective, then $g$ must be surjective. Is it true that $f$ must also be surjective?

*Proof:*  Let $z$ be any arbitrary element in $Z$. We need to find an element $y \in Y$ such that $z=g(y)$. Now, $g\circ f$ surjective means that for $z$, there exists a $x\in X$ such that $z = g(f(x))$. Take $y := f(x)$, then we have a $y\in Y$  such that $z = g(y)$. 
So for any arbitrary element  $z$ taken in $Z$, we can find a corresponding $y\in Y$ such that $z = g(y)$, and that means $g$ is surjective and $f$ need not be be surjective. $\square$   


**Exercise 3.3.6.** Let $f:X\mapsto Y$ be a bijective function, and let $f^{-1}:Y\mapsto X$ be its inverse. Verify the cancellation laws $f^{-1}(f(x)) = x$ for all $x \in X$ and $f(f^{-1}(y)) = y$ for all $y \in Y$. Conclude that $f^{-1}$ is also invertible, and has $f$ as its inverse (thus $(f^{-1} )^{-1} = f$).

*Proof:* Let $y$ be any abitrary element in $Y$, then there exists exactly one $x$ such that $y=f(x)$. But that $x = f^{-1}(y)$ (by definition of inverse function) so that $y = f(f^{-1}(y))$ and $x = f^{-1}(f(x))$. 

Next we show that $f^{-1}$ is invertible i.e we need to show that $f^{-1}$ is injective and surjective. Let $y, \ y' \in Y$ such that $f^{-1}(y) = f^{-1}(y')$, we want to show that $y = y'$ for the injective property. Since $f^{-1}(y) = f^{-1}(y')$, then $f(f^{-1}(y)) = f(f^{-1}(y'))$ and using the cancellation law $y = f(f^{-1}(y))$, then $y = y'$ so $f^{-1}$ is injective. To show the surjective properperty,  let $x \in X$, we need to show that $\exists\ y \in Y$ such that $x = f^{-1}(y)$. Take $y:=f(x)$ so that $x=f^{-1}(f(x))$. So $f^{-1}$ is surjective.

Finally, we need to show that $f$ is the inverse of $f^{-1}$. Let $g$ be the inverse of $f^{-1}$. Then we want to show that $g(x) = f(x)$ for all $x \in X$. Fix an arbitrary element $x\in X$, by the definition of inverse function, there is exactly one $y \in Y$ such that for the fixed $x$, $x = f^{-1}(y)$ and this value of $y$ is $g(x)$, i.e $y = g(x)$. Using the cancellation law $y = f(f^{-1}(y))$, we have that $f(f^{-1}(y)) = g(x)$. But $x = f^{-1}(y)$ so $f(x) = g(x)$. Consequently, for any $x\in X$, we have that $f(x) = g(x)$ so $f$ is the inverse of $f^{-1}$. $\square$            

**Exercise 3.3.7**

**Exercise 3.3.8**

## 3.4














 